# TCL File Generated by Component Editor 22.1
# Mon Apr 03 20:21:49 EDT 2023
# DO NOT MODIFY


# 
# avalon_st_to_sdram_write "Avalon ST to SDRAM Write" v1.0
#  2023.04.03.20:21:49
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_st_to_sdram_write
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_st_to_sdram_write
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon ST to SDRAM Write"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_st_to_sdram_write
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_st_to_sdram_write.v VERILOG PATH avalon_st_to_sdram_write.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_st_to_sdram_write
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_st_to_sdram_write.v VERILOG PATH avalon_st_to_sdram_write.v

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avalon_st_to_sdram_write
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_st_to_sdram_write.v VERILOG PATH avalon_st_to_sdram_write.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits WORDS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master mm_addr address Output 27
add_interface_port avalon_master mm_byteenable byteenable Output 32
add_interface_port avalon_master mm_burstcount burstcount Output 8
add_interface_port avalon_master mm_write write Output 1
add_interface_port avalon_master mm_writedata writedata Output 256
add_interface_port avalon_master mm_waitrequest waitrequest Input 1


# 
# connection point st_instruction
# 
add_interface st_instruction avalon_streaming end
set_interface_property st_instruction associatedClock clock_sink
set_interface_property st_instruction associatedReset reset_sink
set_interface_property st_instruction dataBitsPerSymbol 32
set_interface_property st_instruction errorDescriptor ""
set_interface_property st_instruction firstSymbolInHighOrderBits true
set_interface_property st_instruction maxChannel 0
set_interface_property st_instruction readyLatency 0
set_interface_property st_instruction ENABLED true
set_interface_property st_instruction EXPORT_OF ""
set_interface_property st_instruction PORT_NAME_MAP ""
set_interface_property st_instruction CMSIS_SVD_VARIABLES ""
set_interface_property st_instruction SVD_ADDRESS_GROUP ""

add_interface_port st_instruction st_instruction_valid valid Input 1
add_interface_port st_instruction st_instruction_ready ready Output 1
add_interface_port st_instruction st_instruction_data data Input 32


# 
# connection point st_data_in
# 
add_interface st_data_in avalon_streaming end
set_interface_property st_data_in associatedClock clock_sink
set_interface_property st_data_in associatedReset reset_sink
set_interface_property st_data_in dataBitsPerSymbol 8
set_interface_property st_data_in errorDescriptor ""
set_interface_property st_data_in firstSymbolInHighOrderBits true
set_interface_property st_data_in maxChannel 0
set_interface_property st_data_in readyLatency 0
set_interface_property st_data_in ENABLED true
set_interface_property st_data_in EXPORT_OF ""
set_interface_property st_data_in PORT_NAME_MAP ""
set_interface_property st_data_in CMSIS_SVD_VARIABLES ""
set_interface_property st_data_in SVD_ADDRESS_GROUP ""

add_interface_port st_data_in st_valid valid Input 1
add_interface_port st_data_in st_data data Input 256
add_interface_port st_data_in st_ready ready Output 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits SYMBOLS
set_interface_property csr associatedClock clock_sink
set_interface_property csr associatedReset reset_sink
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_readdata readdata Output 32
add_interface_port csr csr_address address Input 4
add_interface_port csr csr_read read Input 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0

