# TCL File Generated by Component Editor 22.1
# Wed Apr 05 00:46:59 EDT 2023
# DO NOT MODIFY


# 
# avalon_st_adapter_128_to_256 "Avalon ST adapter 128 to 256" v1.0
#  2023.04.05.00:46:59
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_st_adapter_128_to_256
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_st_adapter_128_to_256
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon ST adapter 128 to 256"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_st_adapter_128_to_256
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_st_adapter_128_to_256.v VERILOG PATH avalon_st_adapter_128_to_256.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point st_in
# 
add_interface st_in avalon_streaming end
set_interface_property st_in associatedClock clock_sink
set_interface_property st_in associatedReset reset_sink
set_interface_property st_in dataBitsPerSymbol 8
set_interface_property st_in errorDescriptor ""
set_interface_property st_in firstSymbolInHighOrderBits true
set_interface_property st_in maxChannel 0
set_interface_property st_in readyLatency 0
set_interface_property st_in ENABLED true
set_interface_property st_in EXPORT_OF ""
set_interface_property st_in PORT_NAME_MAP ""
set_interface_property st_in CMSIS_SVD_VARIABLES ""
set_interface_property st_in SVD_ADDRESS_GROUP ""

add_interface_port st_in st_in_data data Input 128
add_interface_port st_in st_in_valid valid Input 1
add_interface_port st_in st_in_ready ready Output 1


# 
# connection point st_out
# 
add_interface st_out avalon_streaming start
set_interface_property st_out associatedClock clock_sink
set_interface_property st_out associatedReset reset_sink
set_interface_property st_out dataBitsPerSymbol 8
set_interface_property st_out errorDescriptor ""
set_interface_property st_out firstSymbolInHighOrderBits true
set_interface_property st_out maxChannel 0
set_interface_property st_out readyLatency 0
set_interface_property st_out ENABLED true
set_interface_property st_out EXPORT_OF ""
set_interface_property st_out PORT_NAME_MAP ""
set_interface_property st_out CMSIS_SVD_VARIABLES ""
set_interface_property st_out SVD_ADDRESS_GROUP ""

add_interface_port st_out st_out_data data Output 256
add_interface_port st_out st_out_ready ready Input 1
add_interface_port st_out st_out_valid valid Output 1

