# TCL File Generated by Component Editor 22.1
# Sun Apr 02 21:03:31 EDT 2023
# DO NOT MODIFY


# 
# avalon_st_dummy "Avalon-ST dummy" v1.0
#  2023.04.02.21:03:31
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_st_dummy
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_st_dummy
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon-ST dummy"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file new_component.v VERILOG PATH new_component.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point st
# 
add_interface st avalon_streaming start
set_interface_property st associatedClock clock_sink
set_interface_property st associatedReset reset_sink
set_interface_property st dataBitsPerSymbol 8
set_interface_property st errorDescriptor ""
set_interface_property st firstSymbolInHighOrderBits false
set_interface_property st maxChannel 0
set_interface_property st readyLatency 0
set_interface_property st ENABLED true
set_interface_property st EXPORT_OF ""
set_interface_property st PORT_NAME_MAP ""
set_interface_property st CMSIS_SVD_VARIABLES ""
set_interface_property st SVD_ADDRESS_GROUP ""

add_interface_port st st_data data Output 256
add_interface_port st st_ready ready Input 1
add_interface_port st st_valid valid Output 1

